### PR TITLE
todotxtio as dependency

### PR DESCRIPTION
**Pull request by mmartinortiz**
Hi,

I saw the entry about `tasker` on your blog and I decided to check it. First I decided to give it a try without installing an additional PPA, so I decided to clone the repository and run it from there.

I saw that inside `src` there is a reference to the `todotxtio` project that is not downloaded when the repository is cloned. I had problems running `tasker` because of that, so I added `todotxtio` as dependency to the `requirements.txt` file.

Though, here is a PR for those changes :-)

### CODE REVIEW

**Comment by flachica** [comment]
I avoid this changes using this guide https://git-scm.com/book/en/v2/Git-Tools-Submodules but your PR is good for me.

Freeze this dependency is good idea

**Comment by mmartinortiz** [comment]
Why do you use the git submodule instead of using the library as a
dependency?

I would use git submodule if a single project is divided in multiple
repositories, but all the are kind of the same project. (Even in that case,
depending of their dependency and the project, I would go for something
else, like docker compose, for example)

In the case of tasker, it is a python project that requires other libraries
(that may not be hosted in a git repository) so I would never go for git
submodules.

But I'm curious about your reasoning for that choice.

**Comment by flachica** [comment]
Because I focused on other functionalities. I did some PR (Filter by completed, by projects) and this had it with less priority.

Your idea and your PR is good for me

**Comment by mmartinortiz** [comment]
Should we merge, then? :-)

**Comment by flachica** [comment]
Of course!

**Pull request closed without merging**
