### PR TITLE
Track time on your tasks

### PR DESCRIPTION
**Pull request by flachica**
* Added new button on tasks list
* If you start a task, the one that was started automatically stops.

### CODE REVIEW

**Comment by atareao** [comment]
I think that when tasker app is closed, all tasks must be set started_at:0. What do you think?
Otherwise, someone can forget the app is tracking time. Besides when tasker is tracking time, the app icon must change.
I dont' see the other commit.... It's better solution yours... So anyone can do what do

**Comment by atareao** [comment]
Tasker must have some reserved tags. This reserved tags, can be,
* due
* started_at
* total_time
All this tags are fixed tags for every task and every todo.txt file
What do you think?

**Comment by flachica** [comment]
> I think that when tasker app is closed, all tasks must be set started_at:0. What do you think?
> Otherwise, someone can forget the app is tracking time. Besides when tasker is tracking time, the app icon must change.
> I dont' see the other commit.... It's better solution yours... So anyone can do what do

Sounds good to me and I think it's easy. I will do it as soon as possible

**Comment by flachica** [comment]
> Tasker must have some reserved tags. This reserved tags, can be,
> 
>     * due
> 
>     * started_at
> 
>     * total_time
>       All this tags are fixed tags for every task and every todo.txt file
>       What do you think?

Sounds good to me and I think it's easy. I will do it as soon as possible. 


Do you think it would be a good idea to also add the first time the task started in date / time format. Currently, the started_at tag saves the last time it started, which does not have to be the first time a task starts. A task can stop, to make way for another and then start again.

**Comment by flachica** [comment]
> I dont' see the other commit.... It's better solution yours... So anyone can do what do

This is resolved in lastest commit. I will do the next ideas

**Comment by flachica** [comment]
> Tasker must have some reserved tags. This reserved tags, can be,
> 
> * due
> * started_at
> * total_time
>   All this tags are fixed tags for every task and every todo.txt file
>   What do you think?

Solved in last commit

**Pull request merged**
